//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLeegProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Formulier_tt = new HashSet<Formulier_tt>();
        }
    
        public string clientnummer { get; set; }
        public string voornaam { get; set; }
        public string achternaam { get; set; }
        public System.DateTime geboortedatum { get; set; }
        public string Behandelaar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formulier_tt> Formulier_tt { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
