//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLeegProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicatieNiveau
    {
        public string indicatieN_id { get; set; }
        public string gedragsProblematiek { get; set; }
        public string context { get; set; }
        public string escalatie { get; set; }
        public string motivatie { get; set; }
        public string ondersteuning { get; set; }
        public string veranderingen { get; set; }
    }
}
