//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLeegProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicatieVragen
    {
        public int indicatieV_id { get; set; }
        public string vraag { get; set; }
    }
}
