//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLeegProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicatieBehoeften
    {
        public string indicatieB_id { get; set; }
        public string wet { get; set; }
        public string kenmerken_inwoner { get; set; }
        public string doel_ondersteuning { get; set; }
        public string ondersteuning { get; set; }
        public Nullable<bool> jeugd { get; set; }
    }
}
